### ISSUE TITLE
Banking showing ALL transactions, even ones that aren't yours

### ISSUE THREAD

**Issue by fly-man-** [itschip/chip-fivem-banking#1]
https://github.com/itschip/chip-fivem-banking/blob/d6ee063a8d78b878f08d48a1fbc10644b404e81a/server/banking.lua#L102

That might have to be changed to only show the transactions from the player who's calling the function

**Comment by itschip** [comment]
Thanks for letting me know dude, I thought I had changed that lol

**Comment by itschip** [comment]
Fixed now.
